const { createPromptModule } = require("inquirer");

const licenseTypes = [ 
'MIT', 
'zLib License',
'The Unlicense',
'University of Illinois/NCSA Open Source License',
'SIL Open Font License 1.1',
'PostgreSQL License',
'Open Software License 3.0',
'Mozilla Public License 2.0',
'Microsoft Public License',
'LaTeX Project Public License v1.3c',
'ISC',
'GNU Lesser General Public License v3.0',
'GNU Lesser General Public License v2.1',
'GNU Lesser General Public License family',
'GNU General Public License v3.0',
'GNU General Public License v2.0',
'GNU General Public License family',
'GNU Affero General Public License v3.0',
'European Union Public License 1.1',
'Eclipse Public License 2.0',
'Eclipse Public License 1.0',
'Educational Community License v2.0',
'Do What The F*ck You Want To Public License',
'Creative Commons Attribution Share Alike 4.0',
'Creative Commons Attribution 4.0',
'Creative Commons Zero v1.0 Universal',
'Creative Commons license family',
'BSD 3-clause Clear license',
'BSD 3-clause "New" or "Revised" license',
'BSD 2-clause "Simplified" license',
'Boost Software License 1.0',
'Artistic license 2.0',
'Apache license 2.0',
'Academic Free License v3.0',
];

module.exports = licenseTypes;